# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8600f474a85699628629170c57d8e3b92caa21562f5d7fbb879e6c0677d77757b44b221c272aa497d1b74ba7dac20401d528187d937e3ab681e914c44ea95901

test:
  secret_key_base: 61c1316c8b38d783ecc283615d91ec4a1c7bd468527ddd475643bd9c358727d28ba6703656030a99ad6f14f4d7da980dbb9ef53d00105f52d8ff36fda8b2db04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
